### PR TITLE
fixed entry-data remains in database after deleting a entry. fix #88

### LINKED ISSUE #88: Entry-data remains in database after deleting a form entry
Form entry-data associated with a form entry remains in database even after that particular form entry is permanently deleted from Form Entries list.

### PR DESCRIPTION
**Pull request by itowhid06**

### CODE REVIEW

File: includes/functions.php [hunk 1]
```diff
@@ -237,11 +237,19 @@ function weforms_change_entry_status( $entry_id, $status ) {
...
         ), array( '%d' )
     );
+
+    $wpdb->delete(
+        $wpdb->weforms_entrymeta, array(
+            'weforms_entry_id' => $entry_id
+        ), array( '%d' )
+    );
+
+    return;
```
Comment (rafsuntaskin) [inline includes/functions.php]: Should return boolean

File: includes/functions.php [hunk 2]
```diff
@@ -237,11 +237,19 @@ function weforms_change_entry_status( $entry_id, $status ) {
...
     global $wpdb;
 
-    return $wpdb->delete(
+    $wpdb->delete(
         $wpdb->weforms_entries, array(
             'id' => $entry_id
         ), array( '%d' )
     );
+
+    $wpdb->delete(
```
Comment (rafsuntaskin) [inline includes/functions.php]: wrap within  Bool of delete()
